### ISSUE TITLE
WINDOWS/py.exe hates this

### ISSUE THREAD

**Issue by flying-frigate-technologies** [kcunning/gamemaster-scripts#4]
py.exe closes everything the moment it gets to the end of the file which means an `input()` is needed to stop it from doing that (yeah, I hate it too). But even with the `input()` it still crashes this file for some reason. I can't be bothered to figure out why and because it runs just fine in Thony so don't fix it on my account.
Screenshot of the output of py.exe, white bars added by me:
![popgen issue](https://user-images.githubusercontent.com/22994532/80413907-19729d80-88c8-11ea-80de-c96d15d61f05.png)

**Comment by kcunning** [comment]
Any way you can post the full trace back rather than an image?

**Comment by flying-frigate-technologies** [comment]
Sorry this took a while. Here it is:

... added by me
```
C:\Users\...>py.exe "...\gamemaster scripts\general\popgen\population-gen.py"
Generating a town of size 1000
Traceback (most recent call last):
  File "...\gamemaster scripts\general\popgen\population-gen.py", line 655, in <module>
    main()
  File "...\gamemaster scripts\general\popgen\population-gen.py", line 650, in main
    t = Town(n)
  File "...\gamemaster scripts\general\popgen\population-gen.py", line 611, in __init__
    r = Resident()
  File "...\gamemaster scripts\general\popgen\population-gen.py", line 197, in __init__
    self.first_name, self.family_name = self.get_name()
  File "...\gamemaster scripts\general\popgen\population-gen.py", line 137, in get_name
    fnames = self.get_lines(race + "_female_names.txt")
  File "...\gamemaster scripts\general\popgen\population-gen.py", line 112, in get_lines
    with open(fname) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'dwarf_female_names.txt'

C:\Users\...>
```

**Comment by flying-frigate-technologies** [comment]
Okay, it works when it is executed from the directory it is installed in. I guess this is a problem with py.exe 's handling of relative paths and I can't see an easy solution.

**Comment by Rogue-koenig** [comment]
Trying to commin branch, that fix this trouble. Access denied
You only need to add 
"import os" with other imports
and
"fname = os.sep.join([os.sep.join(sys.argv[0].split(os.sep)[:-1]), fname])"  before open files in get_lines in class Resident and class Building (~116 and ~244 lines).
So it will be:
def get_lines(self, fname):
        ''' Gets lines from a file, cleans them up, and returns them.
        '''
        fname = os.sep.join([os.sep.join(sys.argv[0].split(os.sep)[:-1]), fname])
        with open(fname) as f:
            lines = f.readlines()
